"""Export service — generates Word and PDF documents from timeline data."""

import io
import logging
from datetime import datetime

from docx import Document as DocxDocument
from docx.shared import Inches, Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.schemas.event import EventResponse

logger = logging.getLogger(__name__)


async def export_to_docx(
    matter_title: str,
    events: list[EventResponse],
    include_metadata: bool = True,
) -> bytes:
    """Generate a Word document from timeline events."""
    doc = DocxDocument()

    # --- Styles ---
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Times New Roman"
    font.size = Pt(11)
    style.paragraph_format.space_after = Pt(6)
    style.paragraph_format.line_spacing = 1.15

    # --- Title ---
    title = doc.add_heading(f"Chronology of Events", level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"Matter: {matter_title}")
    run.font.size = Pt(12)
    run.font.italic = True

    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = date_para.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y')}")
    run.font.size = Pt(10)
    run.font.color.rgb = __import__("docx.shared").shared.RGBColor(0x66, 0x66, 0x66)  # type: ignore

    doc.add_paragraph("_" * 72)

    # --- Events ---
    for i, event in enumerate(events, 1):
        # Event number + date
        heading = doc.add_heading(f"{i}. {event.date}", level=2)

        # Title
        p = doc.add_paragraph()
        run = p.add_run(event.title)
        run.bold = True

        # Description
        if event.description:
            doc.add_paragraph(event.description)

        # People involved
        if event.people:
            people_p = doc.add_paragraph()
            run = people_p.add_run("People: ")
            run.bold = True
            people_p.add_run(", ".join(event.people))

        # Source reference
        meta_parts = []
        if event.source_filename:
            meta_parts.append(f"Source: {event.source_filename}")
        if event.doc_reference:
            meta_parts.append(f"Reference: {event.doc_reference}")
        if event.confidence is not None:
            meta_parts.append(f"Confidence: {event.confidence:.0%}")

        if meta_parts:
            meta_p = doc.add_paragraph()
            run = meta_p.add_run(" | ".join(meta_parts))
            run.font.size = Pt(9)
            run.font.color.rgb = __import__("docx.shared").shared.RGBColor(0x66, 0x66, 0x66)  # type: ignore

        # Separator
        doc.add_paragraph("─" * 40)

    # --- Footer note ---
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    run = footer.add_run(
        "This chronology was automatically generated by AutoLaw. "
        "Please review and verify all entries before filing."
    )
    run.font.size = Pt(9)
    run.font.italic = True

    # Set margins
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


async def export_to_pdf(
    matter_title: str,
    events: list[EventResponse],
    include_metadata: bool = True,
) -> bytes:
    """Generate a PDF from timeline events using fpdf2."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()

    # --- Title ---
    pdf.set_font("Times", "B", 16)
    pdf.cell(0, 10, "Chronology of Events", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Times", "I", 12)
    pdf.cell(0, 8, f"Matter: {matter_title}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Times", "I", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%B %d, %Y')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    pdf.set_draw_color(150, 150, 150)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(5)

    # --- Events ---
    pdf.set_auto_page_break(auto=True, margin=20)

    for i, event in enumerate(events, 1):
        # Check if we need a new page
        if pdf.get_y() > 240:
            pdf.add_page()

        # Event number + date
        pdf.set_font("Times", "B", 13)
        pdf.cell(0, 7, f"{i}. {event.date}", new_x="LMARGIN", new_y="NEXT")

        # Title
        pdf.set_font("Times", "B", 11)
        pdf.multi_cell(0, 6, event.title)

        # Description
        if event.description:
            pdf.set_font("Times", "", 10)
            pdf.multi_cell(0, 5, event.description)

        # People
        if event.people:
            pdf.set_font("Times", "B", 9)
            pdf.cell(15, 5, "People: ")
            pdf.set_font("Times", "", 9)
            pdf.cell(0, 5, ", ".join(event.people), new_x="LMARGIN", new_y="NEXT")

        # Source metadata
        meta_parts = []
        if event.source_filename:
            meta_parts.append(f"Source: {event.source_filename}")
        if event.doc_reference:
            meta_parts.append(f"Ref: {event.doc_reference}")
        if meta_parts:
            pdf.set_font("Times", "I", 8)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 4, " | ".join(meta_parts), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)

        pdf.ln(3)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(3)

    # --- Footer ---
    pdf.ln(5)
    pdf.set_font("Times", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5,
        "This chronology was automatically generated by AutoLaw. "
        "Please review and verify all entries before filing."
    )

    return pdf.output()
